### Chapter 5. Getting Started With Pandas

## 5.1 Introduction to pandas Data Structure

Series and Data Structure

In [1]:
import pandas as pd

In [2]:
obj = pd.Series([i for i in range(4)])

In [3]:
obj

0    0
1    1
2    2
3    3
dtype: int64

Index and Series Value

In [4]:
obj.index

RangeIndex(start=0, stop=4, step=1)

In [5]:
obj.values

array([0, 1, 2, 3], dtype=int64)

You can assign index as follows

In [9]:
import numpy as np
obj_1 = pd.Series(np.arange(4), ['a', 'b', 'c', 'd'])

In [10]:
obj_1

a    0
b    1
c    2
d    3
dtype: int32

In [11]:
obj_1['a']

0

In [12]:
obj_1[obj_1 > 0]

b    1
c    2
d    3
dtype: int32

    Arithmatic Calculation with numpy built in function

In [13]:
np.exp(obj_1)

a     1.000000
b     2.718282
c     7.389056
d    20.085537
dtype: float64

Create Series with python Dictionary

In [30]:
sdata = {'Ohio': 35000, 'Texas': 71000, 'Oregon': 16000, 'Utah': 5000}
obj_3 = pd.Series(sdata)

What happens if the overiding index is not in the index of Series you overide

In [31]:
states = ['California', 'Ohio', 'Oregon', 'Texas']
obj_4 = pd.Series(sdata, index = states)

In [32]:
obj_4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

isnull / and not null function to detect missing data

In [33]:
pd.isnull(obj_4)

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [34]:
pd.notnull(obj_4)

California    False
Ohio           True
Oregon         True
Texas          True
dtype: bool

A useful Series feature for many applications is that it automatically aligns by index label in arithmetic operations:

In [36]:
obj_3 + obj_4

California         NaN
Ohio           70000.0
Oregon         32000.0
Texas         142000.0
Utah               NaN
dtype: float64

Series object / index object can have a name attribute.

In [37]:
obj_4.name = 'Pop'
obj_4.index.name = 'state'
obj_4

state
California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
Name: Pop, dtype: float64

You can also assign index after the Series object is created.

In [38]:
obj

0    0
1    1
2    2
3    3
dtype: int64

In [40]:
obj.index = ['bob', 'Steve', 'Jeff', 'Ryan']
obj

bob      0
Steve    1
Jeff     2
Ryan     3
dtype: int64

### DataFrame

In [43]:
data = {'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada', 'Nevada'], 'year': [2000, 2001, 2002, 2001, 2002, 2003], 'pop': [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}
frame = pd.DataFrame(data)
frame

pop   state  year
0  1.5    Ohio  2000
1  1.7    Ohio  2001
2  3.6    Ohio  2002
3  2.4  Nevada  2001
4  2.9  Nevada  2002
5  3.2  Nevada  2003

In [44]:
frame.head(1)

pop state  year
0  1.5  Ohio  2000

In [47]:
frame.tail(1)

pop   state  year
5  3.2  Nevada  2003

DataFrame's Columns can be arranged with columns argument in DataFrame function.

In [61]:
frame2 = pd.DataFrame(data, columns = ['year', 'state', 'pop'],
                     index = ['one', 'two', 'three', 'four', 'five', 'six'])

Values in each column can be retiredved as Series either by dict-like notation or by attribute

In [62]:
frame2['state']

one        Ohio
two        Ohio
three      Ohio
four     Nevada
five     Nevada
six      Nevada
Name: state, dtype: object

In [63]:
frame2.year

one      2000
two      2001
three    2002
four     2001
five     2002
six      2003
Name: year, dtype: int64

Row can also be retrieved by position or name with the special loc / iloc attribute

In [64]:
frame2.loc['three']

year     2002
state    Ohio
pop       3.6
Name: three, dtype: object

In [66]:
frame2.iloc[2]

year     2002
state    Ohio
pop       3.6
Name: three, dtype: object

    Please note that iloc attribute is now discouraged.

If you assign a Series, its labels will be realigned exactly to the DataFrame’s index, inserting missing values in any holes:

In [68]:
val = pd.Series([-1.2, -1.5, -1.7], index =[' two', 'four', 'five'])
frame2['debt'] = val
frame2

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7   NaN
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7
six    2003  Nevada  3.2   NaN

Del function is to delete columns in the DataFrame object.

In [69]:
frame2['eastern'] = frame2['state'] == 'Ohio'
frame2

year   state  pop  debt eastern
one    2000    Ohio  1.5   NaN    True
two    2001    Ohio  1.7   NaN    True
three  2002    Ohio  3.6   NaN    True
four   2001  Nevada  2.4  -1.5   False
five   2002  Nevada  2.9  -1.7   False
six    2003  Nevada  3.2   NaN   False

In [70]:
del frame2['eastern']

In [71]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7   NaN
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7
six    2003  Nevada  3.2   NaN

The column returned from indexing a DataFrame is a view on the underlying data, not a copy. Thus, any in-place modifications to the Series will be reflected in the DataFrame.

If the nested dict converted to DataFrame with pandas, pandas interpret
- outer dict: Columns
- inner dict: Index

In [72]:
pop = {' Nevada': {2001: 2.4, 2002: 2.9},'Ohio': {2000: 1.5, 2001: 1.7, 2002: 3.6}}
frame3 = pd.DataFrame(pop)
frame3

Nevada  Ohio
2000      NaN   1.5
2001      2.4   1.7
2002      2.9   3.6

Transpose the DataFrame with attribute 'T'

In [74]:
frame3.T

2000  2001  2002
 Nevada   NaN   2.4   2.9
Ohio      1.5   1.7   3.6

In [76]:
pd.DataFrame(pop, index = [2001,2002,2003])

Nevada  Ohio
2001      2.4   1.7
2002      2.9   3.6
2003      NaN   NaN

Can Assign column name / index name

In [78]:
frame3.index.name = 'year'; frame3.columns.name = 'state'

In [79]:
frame3

state   Nevada  Ohio
year                
2000       NaN   1.5
2001       2.4   1.7
2002       2.9   3.6

In [81]:
frame3.values

array([[ nan,  1.5],
       [ 2.4,  1.7],
       [ 2.9,  3.6]])

In [83]:
frame2.values

array([[2000, 'Ohio', 1.5, nan],
       [2001, 'Ohio', 1.7, nan],
       [2002, 'Ohio', 3.6, nan],
       [2001, 'Nevada', 2.4, -1.5],
       [2002, 'Nevada', 2.9, -1.7],
       [2003, 'Nevada', 3.2, nan]], dtype=object)

### Index Objects

In [84]:
obj = pd.Series( range( 3), index =[' a', 'b', 'c'])

Index objects are immutable and thus can't be modified by the user

In [86]:
obj.index[1] = 3 # Type Error

TypeError: Index does not support mutable operations

In [88]:
labels = pd.Index(np.arange(3))
obj2 = pd.Series([1.5, -2.5, 0], index = labels)
obj2

0    1.5
1   -2.5
2    0.0
dtype: float64

In [91]:
'Ohio' in frame3.columns

True

In [93]:
2003 in frame3.index

False

In [95]:
dup_labels = pd.Index(['foo', 'foo', 'bar', 'bar'])
dup_labels

Index(['foo', 'foo', 'bar', 'bar'], dtype='object')

In [106]:
frame3.index.isin([2000, 2001])

array([ True,  True, False], dtype=bool)

### 5.2 Essential Functionality

### Reindexing

In [110]:
obj = pd.Series([ 4.5, 7.2, -5.3, 3.6], index =['d', 'b', 'a', 'c'])

In [112]:
obj2 = obj.reindex(['a', 'b', 'c', 'd', 'e'])
obj2

a   -5.3
b    7.2
c    3.6
d    4.5
e    NaN
dtype: float64

Reindex row then forward fill NaN Value

In [114]:
obj3 = pd.Series([' blue', 'purple', 'yellow'], index =[ 0, 2, 4])
obj3.reindex(range(6), method = 'ffill')

0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: object

reindex can be used with columns keyword

In [117]:
states = ['Texas', 'Utah', 'California']
frame3.reindex(columns = states)

state  Texas  Utah  California
year                          
2000     NaN   NaN         NaN
2001     NaN   NaN         NaN
2002     NaN   NaN         NaN

### Dropping Entries from an Axis

In [119]:
obj = pd.Series(np.arange(5.), index = ['a', 'b', 'c', 'd', 'e'])
new_obj = obj.drop('c')
new_obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [120]:
data = pd.DataFrame(np.arange(16). reshape((4,4)), index =['Ohio', 'Colorado', 'Utah', 'New York'], columns =['one', 'two', 'three', 'four'])
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [123]:
data[data < 5] 

one  two  three  four
Ohio      0.0  1.0    2.0   3.0
Colorado  4.0  NaN    NaN   NaN
Utah      NaN  NaN    NaN   NaN
New York  NaN  NaN    NaN   NaN

### Selection with loc and iloc

In [124]:
data.loc['Colorado', ['two', 'three']]

two      5
three    6
Name: Colorado, dtype: int32

### Integer Indexes

For more precise handling, use loc(for labels) or iloc(for integers)

In [ ]:
ser = pd.Series(np.arange(3.))
ser2 = pd.Series( np.arange( 3.), index =[' a', 'b', 'c'])

In [128]:
ser[:1]

0    0.0
dtype: float64

In [130]:
ser.loc[:1]

0    0.0
1    1.0
dtype: float64

In [132]:
ser.iloc[:1]

0    0.0
dtype: float64

### Arithmetic and Data Alignment

In [134]:
s1 = pd.Series([ 7.3, -2.5, 3.4, 1.5], index =[' a', 'c', 'd', 'e'])
s2 = pd.Series([-2.1, 3.6, -1.5, 4, 3.1], index =[' a', 'c', 'e', 'f', 'g'])
s1 + s2

 a    5.2
c     1.1
d     NaN
e     0.0
f     NaN
g     NaN
dtype: float64

In [138]:
df1 = pd.DataFrame(np.arange(9.). reshape(( 3, 3)), columns = list('bcd'), index =['Ohio', 'Texas', 'Colorado'])


In [139]:
df2 = pd.DataFrame( np.arange(12.). reshape((4, 3)), columns = list('bde'), index =['Utah', 'Ohio', 'Texas', 'Oregon'])

In [141]:
df1 + df2

b   c     d   e
Colorado  NaN NaN   NaN NaN
Ohio      3.0 NaN   6.0 NaN
Oregon    NaN NaN   NaN NaN
Texas     9.0 NaN  12.0 NaN
Utah      NaN NaN   NaN NaN

If you add DataFrame objects with no column or row labels in common, the result will contain all nulls:

In [142]:
df1 = pd.DataFrame({' A': [1, 2]})
df2 = pd.DataFrame({' B': [3, 4]})

In [143]:
df1 - df2

A   B
0 NaN NaN
1 NaN NaN

In [146]:
df1 = pd.DataFrame(np.arange(12.). reshape((3, 4)), columns = list('abcd'))
df2 = pd.DataFrame(np.arange( 20.). reshape((4, 5)),columns = list('abcde'))

df1.add(df2, fill_value = 0)

a     b     c     d     e
0   0.0   2.0   4.0   6.0   4.0
1   9.0  11.0  13.0  15.0   9.0
2  18.0  20.0  22.0  24.0  14.0
3  15.0  16.0  17.0  18.0  19.0

Methods with 'r' attached means row-wise calcuation

### Function Application and Mapping

Numpy ufuncs(element-wise array methods) also work with pandas objects

In [148]:
frame = pd.DataFrame(np.random.randn(4, 3), columns = list('bde'), index =['Utah', 'Ohio', 'Texas', 'Oregon'])
frame

b         d         e
Utah    0.404903  1.199043  0.815118
Ohio    0.002818  0.479237  0.942592
Texas   1.240834 -1.286434 -1.919315
Oregon -0.419946 -1.189319 -1.215549

In [150]:
np.abs(frame)

b         d         e
Utah    0.404903  1.199043  0.815118
Ohio    0.002818  0.479237  0.942592
Texas   1.240834  1.286434  1.919315
Oregon  0.419946  1.189319  1.215549

Instead of numpy uFunc, lambda also works

In [152]:
f = lambda x: x.max() - x.min()
frame.apply(f)

b    1.660779
d    2.485477
e    2.861908
dtype: float64

In [154]:
frame.apply(f, axis = 'columns')

Utah      0.794140
Ohio      0.939774
Texas     3.160149
Oregon    0.795603
dtype: float64

Apply function need not return a scalar value; it can also return a Series with multiple value

In [157]:
def f(x):
    return pd.Series([x.min(), x.max()], index = ['min', 'max'])

In [159]:
frame.apply(f)

b         d         e
min -0.419946 -1.286434 -1.919315
max  1.240834  1.199043  0.942592

In [161]:
frame.apply(f, axis = 1)

min       max
Utah    0.404903  1.199043
Ohio    0.002818  0.942592
Texas  -1.919315  1.240834
Oregon -1.215549 -0.419946

Element-wise Python functions can be used too!

In [165]:
form = lambda x: '%.2f' % x
frame.applymap(form)

b      d      e
Utah     0.40   1.20   0.82
Ohio     0.00   0.48   0.94
Texas    1.24  -1.29  -1.92
Oregon  -0.42  -1.19  -1.22

The reason for the name applymap is that Series has a map method for applying an element-wise function

In [167]:
frame['e'].map(form)

Utah       0.82
Ohio       0.94
Texas     -1.92
Oregon    -1.22
Name: e, dtype: object

### Sorting and Ranking

In [168]:
obj = pd.Series(range(4), index = ['d', 'a', 'b', 'c'])
obj.sort_index()

a    1
b    2
c    3
d    0
dtype: int32

In [169]:
frame = pd.DataFrame(np.arange(8). reshape((2, 4)), index =['three', 'one'],  columns =['d', 'a', 'b', 'c'])
frame.sort_index()

d  a  b  c
one    4  5  6  7
three  0  1  2  3

Since the column is a kind of index, so you can use sort_index method for columns

In [171]:
frame.sort_index(1)

a  b  c  d
three  1  2  3  0
one    5  6  7  4

In [172]:
frame.sort_index(1, ascending = False)

d  c  b  a
three  0  3  2  1
one    4  7  6  5

Also you can sort the DataFrame or Series with sort_value method

In [173]:
obj = pd.Series([ 4, np.nan, 7, np.nan, -3, 2])
obj.sort_values()

4   -3.0
5    2.0
0    4.0
2    7.0
1    NaN
3    NaN
dtype: float64

In [175]:
obj.sort_values(ascending = False)

2    7.0
0    4.0
5    2.0
4   -3.0
1    NaN
3    NaN
dtype: float64

You can also sort the DataFrame on the values of multiple columns what??

In [177]:
frame = pd.DataFrame({'b': [4,7,-3,2], 'a': [0,1,0,1]})
frame

a  b
0  0  4
1  1  7
2  0 -3
3  1  2

In [179]:
frame.sort_values(by = 'b')

a  b
2  0 -3
3  1  2
0  0  4
1  1  7

In [182]:
frame.sort_values(by = ['a', 'b'])

a  b
2  0 -3
0  0  4
3  1  2
1  1  7

In [187]:
obj = pd.Series([7,-5,7,4,2,0,4])
obj.rank()

0    6.5
1    1.0
2    6.5
3    4.5
4    3.0
5    2.0
6    4.5
dtype: float64

Ranks can also be assigned according to the order in which they’re observed in the data

In [188]:
obj.rank(method = 'first')

0    6.0
1    1.0
2    7.0
3    4.0
4    3.0
5    2.0
6    5.0
dtype: float64

In [191]:
# Assign tie values the maximum rank in the group
obj.rank(ascending = False, method = 'max')

0    2.0
1    7.0
2    2.0
3    4.0
4    5.0
5    6.0
6    4.0
dtype: float64

In [190]:
obj.rank(ascending = False, method = 'min')

0    1.0
1    7.0
2    1.0
3    3.0
4    5.0
5    6.0
6    3.0
dtype: float64

Not surprisingly, row-wise rank also possible

In [192]:
frame = pd.DataFrame({' b': [4.3, 7, -3, 2], 'a': [0, 1, 0, 1],'c': [-2, 5, 8, -2.5]})
frame.rank(axis = 'columns')

b    a    c
0  3.0  2.0  1.0
1  3.0  1.0  2.0
2  1.0  2.0  3.0
3  3.0  2.0  1.0

## 5.3 Summarizing and Computing Descriptive Statistics

In [200]:
df = pd.DataFrame([[ 1.4, np.nan], [7.1, -4.5], [np.nan, np.nan], [0.75, -1.3]], index =['a', 'b', 'c', 'd'], columns =['one', 'two'])
df 

one  two
a  1.40  NaN
b  7.10 -4.5
c   NaN  NaN
d  0.75 -1.3

In [201]:
df.sum()

one    9.25
two   -5.80
dtype: float64

Row-wise calculation 
- Passing axis =' columns' or axis = 1 sums across the columns

In [202]:
df.sum(axis = 'columns')

a    1.40
b    2.60
c    0.00
d   -0.55
dtype: float64

NA values are excluded unless the entire slice (row or column in this case) is NA. This can be disabled with the skipna option:

In [203]:
df.mean(axis = 'columns', skipna = False)

a      NaN
b    1.300
c      NaN
d   -0.275
dtype: float64

Some methods, like idxmin and idxmax, return indirect statistics like the index value where the minimum or maximum values are attained:

In [209]:
df.idxmax()

one    d
two    b
dtype: object

In [210]:
df.idxmin()

one    d
two    b
dtype: object

In [223]:
pd.concat([(df.describe()).loc['25%'],(df.describe()).loc['75%']], keys = ['25%', '75%'])

25%  one    1.075
     two   -3.700
75%  one    4.250
     two   -2.100
dtype: float64

### Uniqe Values, Value Counts, and Membership

In [233]:
obj = pd.Series(['c', 'a', 'd', 'a', 'a', 'b', 'b', 'c', 'c'])
uniques = obj.unique()
uniques

array(['c', 'a', 'd', 'b'], dtype=object)

In [234]:
obj.value_counts()

c    3
a    3
b    2
d    1
dtype: int64

In [235]:
pd.value_counts(obj.values, sort = False)

b    2
a    3
c    3
d    1
dtype: int64

'isin' performs a vectorized set membership check and can be useful in filtering a dataset down to a subset of values in a Series or column in a DataFrame:

In [237]:
mask = obj.isin(['b', 'c'])
obj[mask]

0    c
5    b
6    b
7    c
8    c
dtype: object

Related to isin is the Index.get_indexer method, which gives you an index array from an array of possibly non-distinct values into another array of distinct values:

In [239]:
to_match = pd.Series(['c', 'a', 'b', 'b', 'c', 'a'])
unique_vals = pd.Series(['c', 'b', 'a'])
pd.Index(unique_vals).get_indexer(to_match)

array([0, 2, 1, 1, 0, 2], dtype=int64)

Passing pandas.value_counts to this DataFrame’s apply function

In [240]:
data = pd.DataFrame({'Qu1': [1, 3, 4, 3, 4], 
                     'Qu2': [2, 3, 1, 2, 3], 
                     'Qu3': [1, 5, 2, 4, 4]})
data.apply(pd.value_counts).fillna(0)

Qu1  Qu2  Qu3
1  1.0  1.0  1.0
2  0.0  2.0  1.0
3  2.0  2.0  0.0
4  2.0  0.0  2.0
5  0.0  0.0  1.0